linters-settings:
  cyclop:
    skip-tests: true
    max-complexity: 15
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 110
    statements: 70
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/askiada)
      - localmodule
    custom-order: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  godot:
    capital: true
  goimports:
    local-prefixes: github.com/askiada/go-sql-test
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    disable:
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: UK
  paralleltest:
    ignore-missing-subtests: true # Unfortunately, we can't write t.Run("success", testSuccess)
  unparam:
    check-exported: true
  varnamelen:
    min-name-length: 2
    max-distance: 15

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec # security check is not important in tests
        - dupl # we usually duplicate code in tests
        - bodyclose
        - unparam
        - errcheck
        - govet
        - revive
        - gocritic
        - funlen
        - maintidx
        - wrapcheck
    - path: testing
      linters:
        - errcheck
  fix: true
  exclude-use-default: false
  exclude-dirs:
    - tmp
    - bin
    - scripts

run:
  allow-parallel-runners: true
  tests: true
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - gomnd # Marked as deprecated by golangci-lint. Replaced with mnd
    - execinquery #Marked as deprecated by golangci-lint.
    - depguard # because I don't want to write a dedicated config file.
